/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include "calculadora.h"
#include "algoritmos.h"
#include "analizador.h"
#include "list.h"
#include "stack.h"
stack *aux=NULL;
CLIENT *clnt;
double  *result,*dtp,oo;
char *ctp;
twoOperandos  to;
void popTwo(){
	to.ot=*((double*)aux->object);
	pop(&aux);
	to.oo=*((double*)aux->object);
	pop(&aux);
	result=(double *)malloc(sizeof(double));
}
void resuelve(char *operation){
	if(!strcmp(operation,"+")){
		popTwo();
		*result=*(suma_1(&to, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"-")){
		popTwo();
		*result=*(resta_1(&to, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"*")){
		popTwo();
		*result=*(multiplicacion_1(&to, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"/")){
		popTwo();
		*result=*(divicion_1(&to, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"sen")){
		oo=*((double*)aux->object);
		pop(&aux);
		result=(double *)malloc(sizeof(double));
		*result = *(seno_1(&oo, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"cos")){
		oo=*((double*)aux->object);
		pop(&aux);
		result=(double *)malloc(sizeof(double));
		*result = *(coseno_1(&oo, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"tan")){
		oo=*((double*)aux->object);
		pop(&aux);
		result=(double *)malloc(sizeof(double));
		*result = *(tangente_1(&oo, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"ctg")){
		oo=*((double*)aux->object);
		pop(&aux);
		result=(double *)malloc(sizeof(double));
		*result = *(cotangente_1(&oo, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"sec")){
		oo=*((double*)aux->object);
		pop(&aux);
		result=(double *)malloc(sizeof(double));
		*result = *(secante_1(&oo, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"csc")){
		oo=*((double*)aux->object);
		pop(&aux);
		result=(double *)malloc(sizeof(double));
		*result = *(cosecante_1(&oo, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"log")){
		oo=*((double*)aux->object);
		pop(&aux);
		result=(double *)malloc(sizeof(double));
		*result = *(logaritmonepereano_1(&oo, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
	if(!strcmp(operation,"sqrt")){
		oo=*((double*)aux->object);
		pop(&aux);
		result=(double *)malloc(sizeof(double));
		*result = *(raiz_1(&oo, clnt));
		push(&aux,(void *)result,sizeof(double));
		return ;
	}
}
void calculadora_1(char *host,list *psfj){
#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, AYAN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	for(;psfj!=NULL;psfj=psfj->next){
		if(psfj->nb==sizeof(double)){
			dtp=(double *)malloc(sizeof(double));
			*dtp=*((double *)psfj->object);
			push(&aux,(void *)dtp,sizeof(double));
		}
		else{
			if(psfj->nb==sizeof(char)){
				resuelve((char *)psfj->object);
			}else printf("error type data not found\n");
		}
	}
	//printf("\nresultado %f",*((double*)aux->object));
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif
}
int main(int ari,char **arc){//./a.out -option exprecion host
   if(ari!=4){
      printf("\nerror ejecute como %s -notacion operacion host",arc[0]);
      return 1;
   }
   list *psfj=NULL;
// stack *result=NULL;
   if(!memcmp(arc[1],"-i",2)){
      rmSgns(arc[2]);
      yylex(arc[2],&psfj);
   }else{
		char *token;
      if(!memcmp(arc[1],"-pos",4)){
			if((token=strtok(arc[2],","))!=NULL){
				dtp=(double *)malloc(sizeof(double));
				*dtp=strtod(token,NULL);
				add(&psfj,(void *)dtp,sizeof(double));
			}
			while((token=strtok(NULL,","))!=NULL){
				if(isdigit(token[0])){
					dtp=(double *)malloc(sizeof(double));
					*dtp=strtod(token,NULL);
					add(&psfj,(void *)dtp,sizeof(double));
				}else{
					ctp=(char *)malloc(sizeof(char )*4);
					strcpy(ctp,token);
					add(&psfj,(void *)ctp,sizeof(char));
				}
			}
		}
      else{
         if(!memcmp(arc[1],"-pre",4)){
            printf("\nes prefija");
         }
         else
            printf("\nisnt option");
      }
   }
	calculadora_1 (arc[3],psfj);
   puts("");return 0;
}
