/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <math.h>
#define PI 3.141592654
double toRadians(double grade){
	return ((grade*PI)/180);
}
double *
suma_1_svc(twoOperandos *argp, struct svc_req *rqstp)
{
	static double  result;
	result=argp->oo+argp->ot;
	return &result;
}

double *
resta_1_svc(twoOperandos *argp, struct svc_req *rqstp)
{
	static double  result;
	result=argp->oo-argp->ot;
	return &result;
}

double *
multiplicacion_1_svc(twoOperandos *argp, struct svc_req *rqstp)
{
	static double  result;
	result=argp->oo*argp->ot;
	return &result;
}

double *
divicion_1_svc(twoOperandos *argp, struct svc_req *rqstp)
{
	static double  result;
	if(argp->ot!=0)
		result=argp->oo/argp->ot;
	else
		result=37707;
	return &result;
}

double *
seno_1_svc(double *argp, struct svc_req *rqstp)
{
	static double  result;
	result = sin(toRadians(*argp));
	return &result;
}

double *
coseno_1_svc(double *argp, struct svc_req *rqstp)
{
	static double  result;
	result = cos(toRadians(*argp));
	return &result;
}

double *tangente_1_svc(double *argp, struct svc_req *rqstp){
	static double  result;
	result = tan(toRadians(*argp));
	return &result;
}

double *cotangente_1_svc(double *argp, struct svc_req *rqstp)
{
	static double  result;
	result = pow(tan(toRadians(*argp)),-1);
	return &result;
}

double *
secante_1_svc(double *argp, struct svc_req *rqstp)
{
	static double  result;
	result = pow(cos(toRadians(*argp)),-1);
	return &result;
}

double *
cosecante_1_svc(double *argp, struct svc_req *rqstp)
{
	static double  result;
	result = pow(sin(toRadians(*argp)),-1);
	return &result;
}

double *
raiz_1_svc(double *argp, struct svc_req *rqstp)
{
	static double  result;
	if(*argp<0)
		result=37707;
	else
		result=sqrt(*argp);
	return &result;
}

double *
logaritmonepereano_1_svc(double *argp, struct svc_req *rqstp)
{
	static double  result;
	if(*argp<0)
		result=37707;
	else
		result=log(*argp);
	return &result;
}
