/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_twoOperandos (XDR *xdrs, twoOperandos *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->oo))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->ot))
		 return FALSE;
	return TRUE;
}
